var e = getApp();

Page({
    data: {
        isLoad:true,
        pageResult:{
            list:[
                {
                    "id": 1609,
                    "storeId": 54,
                    "storeName": "阳光养生",
                    "storeAreaInfo": {
                        "provinceId": 8,
                        "provinceName": "广东",
                        "cityId": 92,
                        "cityName": "深圳",
                        "countyId": 890,
                        "countyName": "宝安区"
                    },
                    "memberId": 2909349,
                    "nickname": "佳佳",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210419/202104190301564747.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "康复理疗师",
                    "tag": [
                        "长相漂亮",
                        "积极主动",
                        "价格合理"
                    ],
                    "introduction": "温柔知性，优雅大方，陪您度过难忘的时刻",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1575,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 80.22,
                    "avatarSimilarityText": "本人与照片80.22%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": false,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12955",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 22382,
                    "storeId": 559,
                    "storeName": "伊洛特养生",
                    "storeAreaInfo": {
                        "provinceId": 35,
                        "provinceName": "浙江",
                        "cityId": 413,
                        "cityName": "杭州",
                        "countyId": 3922,
                        "countyName": "余杭区"
                    },
                    "memberId": 1041392,
                    "nickname": "甜宝",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210401/202104010244250869.png?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健理疗师",
                    "tag": [
                        "长相漂亮",
                        "手法一流",
                        "照片真实"
                    ],
                    "introduction": "以精湛的技术，完美的服务，真诚的心让你对我无法忘却，懂你的想法给你所需！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1528,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 80.27,
                    "avatarSimilarityText": "本人与照片80.27%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12872",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 8140,
                    "storeId": 262,
                    "storeName": "粉红豹养生",
                    "storeAreaInfo": {
                        "provinceId": 35,
                        "provinceName": "浙江",
                        "cityId": 413,
                        "cityName": "杭州",
                        "countyId": 3922,
                        "countyName": "余杭区"
                    },
                    "memberId": 422786,
                    "nickname": "小九儿",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20200610/202006100405109032.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "照片真实",
                        "长相漂亮",
                        "准时到达"
                    ],
                    "introduction": "态度热情 服务一流 小哥哥点我哦",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1453,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 83.56,
                    "avatarSimilarityText": "本人与照片83.56%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12870",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 5613,
                    "storeId": 54,
                    "storeName": "阳光养生",
                    "storeAreaInfo": {
                        "provinceId": 8,
                        "provinceName": "广东",
                        "cityId": 92,
                        "cityName": "深圳",
                        "countyId": 890,
                        "countyName": "宝安区"
                    },
                    "memberId": 30369,
                    "nickname": "小幂",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20200516/202005160916343877.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "风雨无阻",
                        "服务专业"
                    ],
                    "introduction": "服务好，人漂亮",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1426,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 82.79,
                    "avatarSimilarityText": "本人与照片82.79%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "三天前",
                    "isFavorite": false,
                    "distance": "12870",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 4098,
                    "storeId": 59,
                    "storeName": "檀府养生",
                    "storeAreaInfo": {
                        "provinceId": 25,
                        "provinceName": "上海",
                        "cityId": 303,
                        "cityName": "上海",
                        "countyId": 2774,
                        "countyName": "浦东新区"
                    },
                    "memberId": 5104116,
                    "nickname": "晴子",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210422/202104220433167074.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "按摩师",
                    "tag": [
                        "颜值爆表",
                        "长相漂亮",
                        "服务专业"
                    ],
                    "introduction": "",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1426,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 76.44,
                    "avatarSimilarityText": "本人与照片76.44%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12952",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 21239,
                    "storeId": 462,
                    "storeName": "圆梦养生",
                    "storeAreaInfo": {
                        "provinceId": 4,
                        "provinceName": "北京",
                        "cityId": 53,
                        "cityName": "北京",
                        "countyId": 537,
                        "countyName": "朝阳区"
                    },
                    "memberId": 4267482,
                    "nickname": "艾嘉",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210324/202103240935400984.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "风雨无阻",
                        "服务专业"
                    ],
                    "introduction": "我是典型的江南女孩儿，温柔体贴，甜美可爱，选我绝对会让您满意，希望为您去除疲劳，期待与您相识。😊",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1312,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 79.26,
                    "avatarSimilarityText": "本人与照片79.26%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12211",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 4699,
                    "storeId": 211,
                    "storeName": "逸轩阁",
                    "storeAreaInfo": {
                        "provinceId": 35,
                        "provinceName": "浙江",
                        "cityId": 413,
                        "cityName": "杭州",
                        "countyId": 3915,
                        "countyName": "江干区"
                    },
                    "memberId": 57301,
                    "nickname": "幺妹",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210330/202103300453445295.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "照片真实",
                        "长相漂亮",
                        "手法一流"
                    ],
                    "introduction": "带你不一样的spa体验，选我不会让你失望、欢迎您的下单体验",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1189,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 72.55,
                    "avatarSimilarityText": "本人与照片72.55%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12860",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 6820,
                    "storeId": 248,
                    "storeName": "绮梦养生",
                    "storeAreaInfo": {
                        "provinceId": 17,
                        "provinceName": "江苏",
                        "cityId": 220,
                        "cityName": "苏州",
                        "countyId": 2149,
                        "countyName": "吴中区"
                    },
                    "memberId": 25149,
                    "nickname": "蜜桃",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210309/202103090351489506.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "风雨无阻",
                        "服务专业"
                    ],
                    "introduction": "青春靓丽，态度热情，手法独特，待客人如上帝，让您感受不一样的spa，期待各位下单体验！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1142,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 80,
                    "avatarSimilarityText": "本人与照片80%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12876",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 4161,
                    "storeId": 188,
                    "storeName": "郡主到家",
                    "storeAreaInfo": {
                        "provinceId": 2,
                        "provinceName": "安徽",
                        "cityId": 42,
                        "cityName": "合肥",
                        "countyId": 471,
                        "countyName": "庐阳区"
                    },
                    "memberId": 4592632,
                    "nickname": "小木",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210329/202103291015055290.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "颜值爆表",
                        "长相漂亮",
                        "态度热情"
                    ],
                    "introduction": "性格乖巧听话  服务认真不偷懒  针对顾客要求 提供专业服务 风里雨里按个摩等你   期待下单",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1078,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 83.35,
                    "avatarSimilarityText": "本人与照片83.35%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12220",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 2133,
                    "storeId": 83,
                    "storeName": "嫚姿健康养生",
                    "storeAreaInfo": {
                        "provinceId": 8,
                        "provinceName": "广东",
                        "cityId": 81,
                        "cityName": "广州",
                        "countyId": 812,
                        "countyName": "南沙区"
                    },
                    "memberId": 26120,
                    "nickname": "蜜桃",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210417/202104170815581847.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "服务专业",
                        "认真负责"
                    ],
                    "introduction": "努力工作，认真服务每一位顾客，希望我接手的顾客都会消除疲劳，好运连连，我是蜜桃儿，期待为您服务",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1058,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 67.06,
                    "avatarSimilarityText": "本人与照片67.06%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": false,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12385",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 17048,
                    "storeId": 440,
                    "storeName": "益身缘",
                    "storeAreaInfo": {
                        "provinceId": 35,
                        "provinceName": "浙江",
                        "cityId": 413,
                        "cityName": "杭州",
                        "countyId": 3915,
                        "countyName": "江干区"
                    },
                    "memberId": 4419221,
                    "nickname": "可可",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210422/202104220719413966.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "风雨无阻",
                        "服务专业"
                    ],
                    "introduction": "服务专业  性格开朗 用最好的技术给你带来不一样的体验  欢迎下单哦",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1032,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 73.32,
                    "avatarSimilarityText": "本人与照片73.32%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "三天前",
                    "isFavorite": false,
                    "distance": "12872",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 6115,
                    "storeId": 207,
                    "storeName": "王婷到家",
                    "storeAreaInfo": {
                        "provinceId": 4,
                        "provinceName": "北京",
                        "cityId": 53,
                        "cityName": "北京",
                        "countyId": 543,
                        "countyName": "海淀区"
                    },
                    "memberId": 3141009,
                    "nickname": "缘缘",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20201207/202012070113271565.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "风雨无阻",
                        "服务专业",
                        "积极主动"
                    ],
                    "introduction": "",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 1016,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 77.62,
                    "avatarSimilarityText": "本人与照片77.62%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": false,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12220",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 8423,
                    "storeId": 280,
                    "storeName": "尊享工坊",
                    "storeAreaInfo": {
                        "provinceId": 17,
                        "provinceName": "江苏",
                        "cityId": 220,
                        "cityName": "苏州",
                        "countyId": 2149,
                        "countyName": "吴中区"
                    },
                    "memberId": 107491,
                    "nickname": "果果",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210423/202104230123104340.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "服务专业",
                        "性格开朗"
                    ],
                    "introduction": "从事SPA养生多年，经验丰富手法一流，服务态度友好，期待您的预约！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 963,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 82.83,
                    "avatarSimilarityText": "本人与照片82.83%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "四天前",
                    "isFavorite": false,
                    "distance": "12879",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 16291,
                    "storeId": 434,
                    "storeName": "西西里养生",
                    "storeAreaInfo": {
                        "provinceId": 20,
                        "provinceName": "辽宁",
                        "cityId": 260,
                        "cityName": "营口",
                        "countyId": 2456,
                        "countyName": "西市区"
                    },
                    "memberId": 473549,
                    "nickname": "阿娇",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210113/202101130309100901.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "风雨无阻",
                        "工具齐全"
                    ],
                    "introduction": "专业的spa 带给您身心愉悦",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 911,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 85.26,
                    "avatarSimilarityText": "本人与照片85.26%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12878",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 1981,
                    "storeId": 87,
                    "storeName": "都市养生",
                    "storeAreaInfo": {
                        "provinceId": 16,
                        "provinceName": "湖南",
                        "cityId": 201,
                        "cityName": "长沙",
                        "countyId": 1979,
                        "countyName": "芙蓉区"
                    },
                    "memberId": 16324,
                    "nickname": "小玟",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210415/202104150502344946.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "照片真实",
                        "手法一流",
                        "长相漂亮"
                    ],
                    "introduction": "以精湛的技术，完美的服务，真诚的心让你对我无法忘却，懂你想法给你所需！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 901,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 86.43,
                    "avatarSimilarityText": "本人与照片86.43%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12248",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 3759,
                    "storeId": 103,
                    "storeName": "佳人相伴到家",
                    "storeAreaInfo": {
                        "provinceId": 16,
                        "provinceName": "湖南",
                        "cityId": 201,
                        "cityName": "长沙",
                        "countyId": 1979,
                        "countyName": "芙蓉区"
                    },
                    "memberId": 28437,
                    "nickname": "青青",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20200821/202008210543117375.jpg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "服务专业",
                        "态度热情",
                        "照片真实"
                    ],
                    "introduction": "一位懂您的技师，让人更轻松。给我一份信任还你一身轻松",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 883,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 87.39,
                    "avatarSimilarityText": "本人与照片87.39%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "一天前",
                    "isFavorite": false,
                    "distance": "12250",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 3249,
                    "storeId": 112,
                    "storeName": "贵妃居养生",
                    "storeAreaInfo": {
                        "provinceId": 28,
                        "provinceName": "四川",
                        "cityId": 344,
                        "cityName": "自贡",
                        "countyId": 3181,
                        "countyName": "贡井区"
                    },
                    "memberId": 4464085,
                    "nickname": "九儿",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210407/202104071000170037.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "服务专业",
                        "手法一流"
                    ],
                    "introduction": "服务认真不偷懒，针对顾客要求，提供专业服务 期待您的下单！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 865,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 77.76,
                    "avatarSimilarityText": "本人与照片77.76%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12220",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 13881,
                    "storeId": 216,
                    "storeName": "恩辰健康养生",
                    "storeAreaInfo": {
                        "provinceId": 14,
                        "provinceName": "河南",
                        "cityId": 180,
                        "cityName": "郑州",
                        "countyId": 1774,
                        "countyName": "二七区"
                    },
                    "memberId": 628602,
                    "nickname": "小月",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210406/202104061239533299.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "风雨无阻",
                        "服务专业",
                        "积极主动"
                    ],
                    "introduction": "",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 839,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 69.97,
                    "avatarSimilarityText": "本人与照片69.97%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "两天前",
                    "isFavorite": false,
                    "distance": "12150",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 39571,
                    "storeId": 529,
                    "storeName": "芬芳养生",
                    "storeAreaInfo": {
                        "provinceId": 8,
                        "provinceName": "广东",
                        "cityId": 92,
                        "cityName": "深圳",
                        "countyId": 4004,
                        "countyName": "龙华区"
                    },
                    "memberId": 380238,
                    "nickname": "允珍",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210108/202101080613237135.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健理疗师",
                    "tag": [
                        "风雨无阻",
                        "服务专业",
                        "积极主动"
                    ],
                    "introduction": "你好，我是允珍，承蒙您的厚爱！",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 832,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 71.39,
                    "avatarSimilarityText": "本人与照片71.39%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": true,
                    "activeTime": "三天前",
                    "isFavorite": false,
                    "distance": "12450",
                    "storeType": 2,
                    "isFar": true
                },
                {
                    "id": 15869,
                    "storeId": 418,
                    "storeName": "小阿俏养生",
                    "storeAreaInfo": {
                        "provinceId": 35,
                        "provinceName": "浙江",
                        "cityId": 413,
                        "cityName": "杭州",
                        "countyId": 3922,
                        "countyName": "余杭区"
                    },
                    "memberId": 4438470,
                    "nickname": "笑笑",
                    "gender": 2,
                    "avatar": "https://oss.angemo.com/upload/20210402/202104021009295030.jpeg?x-oss-process=image/resize,m_fill,w_320,h_320,limit_0/auto-orient,0/quality,q_90",
                    "schedule": null,
                    "starLevel": 5,
                    "professionalTitle": "保健按摩师",
                    "tag": [
                        "长相漂亮",
                        "态度热情",
                        "形象得体"
                    ],
                    "introduction": "形象好 气质佳 欢迎预约体验",
                    "fansNumber": 0,
                    "viewNumber": 0,
                    "orderQuantity": 820,
                    "currentState": 2,
                    "currentStateDescription": "可预约",
                    "isStore": false,
                    "isVisit": true,
                    "isVerify": true,
                    "isAvatarAuth": true,
                    "avatarSimilarity": 73.73,
                    "avatarSimilarityText": "本人与照片73.73%相似",
                    "isRealnameAuth": true,
                    "isGoodTechnique": false,
                    "activeTime": "三天前",
                    "isFavorite": false,
                    "distance": "12868",
                    "storeType": 2,
                    "isFar": true
                }
            ],
        },
        storeList:[
            {
                "id": 259,
                "name": "悠韵到家",
                "photo": "https://oss.angemo.com/upload/20200517/202005171130118648.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "四川省成都市成华区昭觉寺南路50栋3栋3层附302号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 4033,
                "contactName": "李佳琴",
                "contactNumber": "17313179100",
                "longitude": 104.06608433315498,
                "latitude": 30.61848496902774,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 108
            },
            {
                "id": 216,
                "name": "恩辰健康养生",
                "photo": "https://oss.angemo.com/upload/20191207/201912070912061417.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "深圳市龙岗区南湾街道南岭村社区金坑北路7号金龙花园C栋107C铺元1806",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 3585,
                "contactName": "陈瑞",
                "contactNumber": "15515904239",
                "longitude": 113.6538968122842,
                "latitude": 34.75814763002644,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 78,
                "name": "舒适到家",
                "photo": "https://oss.angemo.com/upload/20191011/201910110546559312.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "上海市奉贤区金汇工业区1390号4幢4065",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 1753,
                "contactName": "卞骏",
                "contactNumber": "19921336970",
                "longitude": 121.49285,
                "latitude": 31.148825,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 258,
                "name": "春瑟",
                "photo": "https://oss.angemo.com/upload/20200311/202003110450361524.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "韶关市浈江区乐园镇新村北区韶赣高速方向A区16号之三",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 1785,
                "contactName": "廖小琼",
                "contactNumber": "18514669311",
                "longitude": 112.496788,
                "latitude": 37.852264,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 323,
                "name": "娇兰养生",
                "photo": "https://oss.angemo.com/upload/20200413/202004130953203537.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "深圳市罗湖区桂园街道桂木园社区桂园路141号红群楼18栋二单元103",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 1312,
                "contactName": "秦水青",
                "contactNumber": "13312932954",
                "longitude": 113.7980562095538,
                "latitude": 23.06788754754107,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 322,
                "name": "香格养生",
                "photo": "https://oss.angemo.com/upload/20200413/202004130538358723.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "山东省青岛市市南区香港中路65—2号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 1179,
                "contactName": "刘红利",
                "contactNumber": "15063902317",
                "longitude": 120.40854,
                "latitude": 36.068263,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 212,
                "name": "叮噔到家",
                "photo": "https://oss.angemo.com/upload/20191205/201912050356591694.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "西安市莲湖区劳动南路72号3-2号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 597,
                "contactName": "张莉",
                "contactNumber": "18192531491",
                "longitude": 108.86764955401037,
                "latitude": 34.266142734209005,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 30
            },
            {
                "id": 285,
                "name": "维密养生",
                "photo": "https://oss.angemo.com/upload/20200325/202003250317164669.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "深圳市罗湖区东晓街道独树社区太白路4017号中华花园1栋、2栋、裙楼1栋30306号商铺",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 5395,
                "contactName": "乔雯香",
                "contactNumber": "15034097073",
                "longitude": 112.50180512768702,
                "latitude": 37.95006284430088,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 460,
                "name": "常颜道养生",
                "photo": "https://oss.angemo.com/upload/20210221/202102210425504246.png?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "浙江省湖州市安吉县昌硕街道花鸟市场114号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 1352,
                "contactName": "田湉",
                "contactNumber": "18257213663",
                "longitude": 113.803715,
                "latitude": 23.039,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 30
            },
            {
                "id": 497,
                "name": "开心到家",
                "photo": "https://oss.angemo.com/upload/20200622/202006220435302767.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "武汉市江岸区百步亭温馨苑C区507栋112室",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 778,
                "contactName": "尤丽丽",
                "contactNumber": "13387666171",
                "longitude": 114.127801,
                "latitude": 22.60742,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 38
            },
            {
                "id": 467,
                "name": "丽思卡尔高端养生",
                "photo": "https://oss.angemo.com/upload/20201028/202010280855238582.jpeg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "上海市奉贤区金碧路1998弄3号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 441,
                "contactName": "戴弟",
                "contactNumber": "18521535115",
                "longitude": 121.4254150390625,
                "latitude": 31.154464721679677,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 382,
                "name": "美一尔养生",
                "photo": "https://oss.angemo.com/upload/20200513/202005130401082202.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "福建省晋江市塘岸街302号梅龙小区7幢",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 363,
                "contactName": "陶小燕",
                "contactNumber": "13751371276",
                "longitude": 114.12786865234378,
                "latitude": 22.607524871826154,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 504,
                "name": "紫御养生",
                "photo": "https://oss.angemo.com/upload/20200712/202007120545089278.jpeg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "甘肃省天水市秦州区财政局家属院一单元102",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 738,
                "contactName": "于瑞娟",
                "contactNumber": "13501308097",
                "longitude": 113.6395568847657,
                "latitude": 22.84804534912108,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 50
            },
            {
                "id": 535,
                "name": "东升养生",
                "photo": "https://oss.angemo.com/upload/20200701/202007010510278153.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "辽宁省沈阳市皇姑区鸭绿江街21-3号",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 721,
                "contactName": "李国峰",
                "contactNumber": "18342418407",
                "longitude": 123.45944893749868,
                "latitude": 41.84014448562855,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 30
            },
            {
                "id": 546,
                "name": "妙韵养生",
                "photo": "https://oss.angemo.com/upload/20200706/202007060537171199.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "河北省石家庄市长安区丰收路186号汇龙湾1-2-3001",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 302,
                "contactName": "武春彦",
                "contactNumber": "13780316772",
                "longitude": 114.127618,
                "latitude": 22.607237,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 560,
                "name": "九和源养生",
                "photo": "https://oss.angemo.com/upload/20200713/202007130400383765.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "南昌市青山湖区顺外村416店面",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 578,
                "contactName": "梁小莹",
                "contactNumber": "18000215813",
                "longitude": 115.939311405572,
                "latitude": 28.67375443152804,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 59,
                "name": "檀府养生",
                "photo": "https://oss.angemo.com/upload/20210424/202104241253546693.jpeg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "上海市奉贤区金碧路1990号1层",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 4161,
                "contactName": "吉晓玲",
                "contactNumber": "15618719557",
                "longitude": 121.47287721688227,
                "latitude": 31.23253378354108,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 66,
                "name": "蝶雅养生",
                "photo": "https://oss.angemo.com/upload/20191009/201910090433031898.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "上海市奉贤区奉浦工业区奉浦大道111号六楼3376室",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 526,
                "contactName": "高青",
                "contactNumber": "13918775889",
                "longitude": 121.42333316665786,
                "latitude": 31.195701518384578,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 30
            },
            {
                "id": 22,
                "name": "相遇养生",
                "photo": "https://oss.angemo.com/upload/20190312/201903120742440437.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "深圳市龙岗区布吉街道西环路金沙大厦904B室",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 2953,
                "contactName": "张艳",
                "contactNumber": "13538059641",
                "longitude": 114.12422180175778,
                "latitude": 22.60358047485352,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 0
            },
            {
                "id": 30,
                "name": "千寻养生",
                "photo": "https://oss.angemo.com/upload/20190604/201906040220138696.jpg?x-oss-process=image/resize,m_fill,w_320,h_180,limit_0/auto-orient,0/quality,q_90",
                "address": "深圳市福田区南园街道东园社区红岭南路1039号红岭大厦5栋21D",
                "telephone": null,
                "businessHours": null,
                "orderQuantity": 854,
                "contactName": "朱丹",
                "contactNumber": "13058198591",
                "longitude": 114.057868,
                "latitude": 22.543099,
                "isVisit": true,
                "distance": "0",
                "defaultCouponPrice": 0,
                "defaultCouponAmount": 30
            }
        ],
        status: {
            isShowMask: !1,
            isShowStoreOption: !1,
            isShowWhereOption: !1,
            isShowSortOption: !1
        },
        pageParam: {
            isVisit: !0,
            longitude: 0,
            latitude: 0,
            page: 0,
            pageSize: 10,
            gender: 0,
        },
        iPhoneX: !!e.globalData.iPhoneX,
    },
    onLoad: function(t) {
        wx.setNavigationBarTitle({
            title: "技师列表"
        })
        wx.hideNavigationBarLoading()
        this.setData({
            isLoad:false
        })
    },
    
    switchStore: function() {
        var e = this, t = e.data.status;
        t.isShowStoreOption ? (t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, 
        t.isShowSortOption = !1) : (t.isShowMask = !0, t.isShowStoreOption = !0, t.isShowWhereOption = !1, 
        t.isShowSortOption = !1), e.setData({
            status: t
        });
    },
    switchWhere: function() {
        var e = this, t = e.data.pageParam;
        t.tempWhere = t.where || 0;
        var a = e.data.status;
        a.isShowWhereOption ? (a.isShowMask = !1, a.isShowStoreOption = !1, a.isShowWhereOption = !1, 
        a.isShowSortOption = !1) : (a.isShowMask = !0, a.isShowStoreOption = !1, a.isShowWhereOption = !0, 
        a.isShowSortOption = !1), e.setData({
            status: a,
            pageParam: t
        });
    },
    setGender: function(e) {
        var t = this, a = t.data.pageParam;
        e.currentTarget.dataset.id == a.gender && -1 != a.gender ? a.gender = 0 : -1 == a.gender ? a.gender = 1 == e.currentTarget.dataset.id ? 2 : 1 : e.currentTarget.dataset.id != a.gender && a.gender ? a.gender = -1 : a.gender = e.currentTarget.dataset.id, 
        t.setData({
            pageParam: a
        });
    },
    switchSort: function() {
        var e = this, t = e.data.status;
        t.isShowSortOption ? (t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, 
        t.isShowSortOption = !1) : (t.isShowMask = !0, t.isShowStoreOption = !1, t.isShowWhereOption = !1, 
        t.isShowSortOption = !0), e.setData({
            status: t
        });
    },
    setStoreIds: function(e) {
        var t = this, a = parseInt(e.currentTarget.dataset.id), i = t.data.storeList;
        i.forEach(function(e) {
            a == e.id && (e.isChecked = !e.isChecked);
        }), t.setData({
            storeList: i
        });
    },
    confirmStoreIds: function() {
        var e = this, t = e.data.status, a = e.data.pageParam, i = e.data.pageResult, s = e.data.storeList, r = "", o = "";
        s && s.length > 0 ? s.forEach(function(e) {
            e.isChecked && (0 == o.length ? (r = e.id, o = e.name) : (r += "," + e.id, o += "+" + e.name));
        }) : e.setData({
            storeIds: "",
            storeNames: ""
        }), t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, t.isShowSortOption = !1, 
        a.storeIds = r, a.page = 0, i.list = [], i.isEmpty = !1, i.isFinish = !1, e.setData({
            status: t,
            pageParam: a,
            pageResult: i,
            storeList: s,
            storeNames: o
        }), e.loadList();
    },
    setWhere: function(e) {
        var t = this, a = (t.data.status, t.data.pageParam), i = (t.data.pageResult, parseInt(e.currentTarget.dataset.id));
        console.log(i), a.tempWhere = a.tempWhere || 0, a.whereName = "", (a.tempWhere & i) == i ? a.tempWhere = a.tempWhere & ~i : a.tempWhere = a.tempWhere | i, 
        t.setData({
            pageParam: a
        });
    },
    confirmWhere: function() {
        var e = this, t = e.data.status, a = e.data.pageParam, i = e.data.pageResult;
        a.where = a.tempWhere || 0, a.whereName = "", a.isMobileAuth = !1, a.isAvatarAuth = !1, 
        a.isRealnameAuth = !1, a.isSetAlbum = !1, a.where > 0 && (1 == (1 & a.where) && ("" == a.whereName ? a.whereName += "手机认证" : a.whereName += "+手机认证", 
        a.isMobileAuth = !0), 2 == (2 & a.where) && ("" == a.whereName ? a.whereName += "头像认证" : a.whereName += "+头像认证", 
        a.isAvatarAuth = !0), 4 == (4 & a.where) && ("" == a.whereName ? a.whereName += "实名认证" : a.whereName += "+实名认证", 
        a.isRealnameAuth = !0), 8 == (8 & a.where) && ("" == a.whereName ? a.whereName += "多张照片" : a.whereName += "+多张照片", 
        a.isSetAlbum = !0)), t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, 
        t.isShowSortOption = !1, a.page = 0, i.list = [], i.isEmpty = !1, i.isFinish = !1, 
        e.setData({
            status: t,
            pageParam: a,
            pageResult: i
        }), e.loadList();
    },
    setOrderType: function(e) {
        var t = this, a = t.data.status, i = t.data.pageParam, s = t.data.pageResult, r = [ "", "系统推荐", "销量最高", "距离最近", "最新加入" ];
        a.isShowMask = !1, a.isShowStoreOption = !1, a.isShowWhereOption = !1, a.isShowSortOption = !1, 
        i.orderType != parseInt(e.currentTarget.dataset.id) ? (i.orderType = parseInt(e.currentTarget.dataset.id), 
        i.orderTypeName = r[parseInt(e.currentTarget.dataset.id)]) : (i.orderType = 0, i.orderTypeName = ""), 
        i.page = 0, s.list = [], s.isEmpty = !1, s.isFinish = !1, t.setData({
            status: a,
            pageParam: i,
            pageResult: s
        }), t.loadList();
    },
    reset: function() {
        var e = this, t = e.data.status, a = e.data.pageParam, i = e.data.pageResult, s = e.data.storeList;
        s.forEach(function(e) {
            e.isChecked = !1;
        }), t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, t.isShowSortOption = !1, 
        a.storeIds = "", a.tempWhere = 0, a.where = 0, a.gender = 0, a.whereName = "", a.isMobileAuth = !1, 
        a.isAvatarAuth = !1, a.isRealnameAuth = !1, a.isSetAlbum = !1, a.page = 0, i.list = [], 
        i.isEmpty = !1, i.isFinish = !1, e.setData({
            status: t,
            pageParam: a,
            pageResult: i,
            storeList: s,
            storeNames: ""
        }), e.loadList();
    },
    close: function() {
        var e = this, t = e.data.status;
        t.isShowMask = !1, t.isShowStoreOption = !1, t.isShowWhereOption = !1, t.isShowSortOption = !1, 
        e.setData({
            status: t
        });
    },
    toProject: function(a) {
        var e = a.currentTarget.dataset.id;
        wx.navigateTo({
            url: "/weixinmao_jz/pages/project/index?id=" + e
        });
    },
    onReady: function() {},
    bindInput: function(a) {
        var t = this;
        this.setData({
            inputValue: a.detail.value
        }), t.onShow();
    },
    onShow: function() {
        // tabbar
        if (typeof this.getTabBar === 'function' &&
            this.getTabBar()) {
            this.getTabBar().setData({
              selected: 1
            })
        }
    },
    onHide: function() {},
    onUnload: function() {},
    // 下拉刷新
    onPullDownRefresh: function() {
        wx.showNavigationBarLoading();
        this.onLoad();
    },
    doCall: function() {
        var a = this.data.textData.shop_tel;
        wx.makePhoneCall({
            phoneNumber: a
        });
    },
    onShareAppMessage: function() {
        return {
            title: wx.getStorageSync("companyinfo").name,
            path: "/weixinmao_jz/pages/index/index"
        };
    }
});